/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.32.4-gdff50fa (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.32.4-gdff50fa"
#endif
#define SDL_REVISION_NUMBER 0
